# Generated by Django 2.2.1 on 2019-06-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20190622_1201'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='car',
            new_name='mark',
        ),
        migrations.AddField(
            model_name='announcement',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cars.ModelCar'),
        ),
    ]
