# Generated by Django 2.2.1 on 2019-06-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190622_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.ModelCar'),
        ),
    ]
