# Generated by Django 2.2.1 on 2019-06-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20190622_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year_of_issue',
        ),
    ]
